index:
    path: /
    controller: App\Controller\PostController:article

articles:
  path: articles/{_locale}/{year}/{article}.{_format}
  defaults: { _controller: App\Controller\PostController:article,  _format: html}
  requirements:
    year: \d{4}
    _locale: es|en|fr
    _format: html|rss
  